services:
  jubilappdb:
    image: postgres:16
    container_name: jubilappdb
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - jubilapp-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jubilappdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jubilapp-api
    depends_on:
      jubilappdb:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "4000:3000"
    networks:
      - jubilapp-network

networks:
  jubilapp-network:
    driver: bridge
